# Data Extraction

##  Step 1: Data is extracted using Youtube API on Appscript, imported as an excel sheet.
//Code for Keyword Search  : Js code

function YouTubeData() {
  var spreadSheet = SpreadsheetApp.getActiveSpreadsheet();
  var activeSheet = spreadSheet.getActiveSheet();
  
  var search = YouTube.Search.list("snippet, id", {q: "Data Science", maxResults: 50});
  var videoIds = search.items.map(item => item.id.videoId).join(",");

  var videoDetails = YouTube.Videos.list("snippet,statistics", {id: videoIds});
  var channelDetails = YouTube.Channels.list("snippet,statistics", {id: videoDetails.items.map(item => item.snippet.channelId).join(",")});

  var data = videoDetails.items.map(video => {
    var channel = channelDetails.items.find(channel => channel.id === video.snippet.channelId);
    return [video.id, video.snippet.title, channel.snippet.title, video.statistics.viewCount, video.statistics.likeCount, video.statistics.commentCount, channel.statistics.subscriberCount];
  });

  activeSheet.getRange(2, 1, data.length, data[0].length).setValues(data);
}


#### Google Apps Script code for a YouTube scraper that uses the YouTube API to gather information about videos related to "data science". The code searches for videos, retrieves the video IDs, and then gets the video information such as the title, channel name, subscriber count, view count, like count, dislike count, and comment count. The retrieved information is then written to a Google Sheet.

# Data Cleaning and Processing

In [40]:
import pandas as pd
import numpy as np

# Visvalization
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

In [41]:
ds = pd.read_excel(r'C:\Users\Rizwanaa\OneDrive\Desktop\Data_Science.xlsx')

In [42]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Video_ID          50 non-null     object
 1   Channel_Ttile     50 non-null     object
 2   Channel_Name      50 non-null     object
 3   View_Count        50 non-null     int64
 4   Like_Count        50 non-null     int64
 5   Comment_Count     50 non-null     int64
 6   Subscriber_Count  50 non-null     int64
dtypes: int64(4), object(3)
memory usage: 2.9+ KB

In [43]:
ds.isnull().any()

Video_ID            False
Channel_Ttile       False
Channel_Name        False
View_Count          False
Like_Count          False
Comment_Count       False
Subscriber_Count    False
dtype: bool

In [44]:
ds = pd.DataFrame(ds)

In [45]:
ds.tail()

,Video_ID,Channel_Ttile,Channel_Name,View_Count,Like_Count,Comment_Count,Subscriber_Count
45,Z79AqDouS-Y,How I'd Learn Data Science In 2023 (If I Could...,Data Nash,3139,233,35,4150
46,T08eJt9DlgU,Data Scientist vs Data Analyst - Which Is Righ...,CareerFoundry,10870,372,12,158000
47,pLon_Mit7sk,day in the life of a Business Analyst at Spoti...,Lillian Chiu,246153,6975,246,173000
48,HqoLnQ0X-F8,Full Data Science Roadmap for Beginner,Ayush Singh,47227,1889,117,35900
49,qrhRfPY4F4w,The most important skills of data scientists |...,TEDx Talks,250949,3889,94,37500000

In [46]:
ds.shape

(50, 7)

In [47]:
ds.size

350

In [48]:
ds.columns

Index(['Video_ID ', 'Channel_Ttile', 'Channel_Name', 'View_Count',
       'Like_Count', 'Comment_Count', 'Subscriber_Count'],
      dtype='object')

In [49]:
len(ds)

50

In [50]:
ds

,Video_ID,Channel_Ttile,Channel_Name,View_Count,Like_Count,Comment_Count,Subscriber_Count
0,X3paOmcrTjQ,Data Science In 5 Minutes | Data Science For B...,Simplilearn,3231797,47521,1085,2800000
1,RBSUwFGa6Fk,What is Data Science?,IBM Technology,60188,1990,47,379000
2,ua-CiDNNj30,Learn Data Science Tutorial - Full Course for ...,freeCodeCamp.org,2504045,57663,945,7180000
3,xC-c7E5PK0Y,What REALLY is Data Science? Told by a Data Sc...,Joma Tech,3277329,126792,3645,2080000
4,-ETQ97mXXF0,Data Science Full Course - Learn Data Science ...,edureka!,2992711,63014,673,3690000
5,ZWgRvW8d_N4,How I Would Learn Data Science in 2023? (If I ...,Sundas Khalid,57616,2575,124,109000
6,t6CD1EwU5kc,How I Would NOT Learn Data Science in 2023.,Ken Jee,65164,2509,195,235000
7,pn0PUY0jwGQ,The Harsh Reality of Being a Data Scientist,Sundas Khalid,364605,6944,965,109000
8,0w9BAIVGuCA,How I Would Learn Data Science in 2023 (if I h...,Internet Made Coder,7642,462,43,208000
9,ho9vNL4MYZ8,Top Courses to Learn Data Science Skills FAST!,Thu Vu data analytics,88502,4886,137,118000
10,rGx1QNdYzvs,FREE Data Analyst Bootcamp!!,Alex The Analyst,29882,4184,435,368000
11,sOZ8MxFw8TQ,Why you should not be a data scientist,Tina Huang,661960,18882,928,454000
12,f3FnCoKWmBg,How I'd Learn Data Analytics in 2023 (If I Had...,CareerFoundry,377700,13790,395,158000
13,x9PlR2CLxwY,Data Science Roadmap 2023 👨‍💻👩‍💻,Rafa Gonzalez Gouveia,12140,1136,69,55400
14,xiEC5oFsq2s,Data Science Full Course - 12 Hours | Data Sci...,edureka!,16080,489,3,3690000
15,QnGotm29cZE,Full Stack Data Science Roadmap 2023,Thu Vu data analytics,110960,4407,145,118000
16,O9nf1CqjGzI,Data Science Career: (Is Becoming A Data Scien...,Shane Hummus,108786,4478,293,365000
17,LHBE6Q9XlzI,Python for Data Science - Course for Beginners...,freeCodeCamp.org,2666741,65342,1262,7180000
18,eaFaD_IBYW4,Data Science Roadmap 2023 | Learn Data Science...,codebasics,42340,2480,206,737000
19,4UOIWO8AaqU,"DATA SCIENCE с НУЛЯ - Скиллы, задачи, зарплаты...",Noukash,39219,1628,96,64400
20,xvEKQefqQ7A,🔥Data Science Full Course 2022 | Data Science ...,Simplilearn,338337,5720,49,2800000
21,Rt6eb9VOFII,How I Would Learn Data Science in 2022,Recall by Dataiku,217855,10503,160,50800
22,N6BghzuFLIg,Intro to Data Science - Crash Course for Begin...,freeCodeCamp.org,360367,7508,140,7180000
23,hucuMCZBbIY,ChatGPT Is Replacing Data Scientists? 🤯,Thu Vu data analytics,22232,913,110,118000
24,9IZCNnuGI9k,How Data Scientists can use ChatGPT,Jay Feng,255,23,1,32500
25,KxryzSO1Fjs,What is Data Science? | Introduction to Data S...,Simplilearn,443112,6059,340,2800000
26,hv6jonYDwzI,Кем стать в Data Science?,karpov.courses,14393,591,37,31900
27,BSBpwS4hBgM,The Most Important Curve in Data Science,ritvikmath,2481,163,19,107000
28,jtn-hRJjl68,What is Data Science? | Complete RoadMap | Sim...,Apna College,1305937,65920,2024,3280000
29,NWzbdWf7Yts,6 Months Data Science RoadMap 2023,Krish Naik,58059,2134,181,716000
30,FOefO43CsZo,ما هي علوم البيانات Data Science,Mohamed Al Assaal - اتعلم مع العسال,11978,683,37,343000
31,PD8VGZjfI9Y,Data science - كل ما تود معرفته عن مجال علم ال...,Norhan Zeid,49928,3169,208,5400
32,nkvInnpuic8,Can I learn data science if I am more than 30?,codebasics,3459,268,68,737000
33,uFTd2b23GvI,Best Data Science Books for Beginners 📚,Thu Vu data analytics,192567,10817,217,118000
34,jmECuuw28wI,10 raisons de ne PAS devenir Data Scientist.,Defend Intelligence,45692,1935,90,111000
35,VykLcJ0kdB4,علم البيانات - المختصر المفيد,Ali Shahin,65915,5833,119,390000
36,kpi9hFZ15Gk,La VÉRITÉ sur la DATA SCIENCE Au Canada 🇨🇦,Data From Scratch - Willis,7368,383,39,3870
37,AEl7oIYAyDo,Data Science Job Market Predictions for 2023 p...,Jay Feng,642,29,1,32500
38,jd1pbjANUjY,КАК Я СТАЛА ПРОГРАММИСТОМ (data science) / Как...,Julia In July,1222,80,56,524
39,AI1eKN1Eldg,FASTEST Way to Learn Data Science and ACTUALLY...,Power Couple,49443,2338,136,275000
40,LsXpdPvtKOE,🔥Develop Your Data Science Career With the IIT...,Simplilearn,1230,18,0,2800000
41,cyXkzCJ0XZI,"Data Science что это? Что нужно знать, чтобы с...",Be Geek,4785,116,37,46600
42,DIkXhX2ixJk,Big Data et Data Science : quelles sont les di...,D4 DATA,5380,259,27,753
43,8vOR_LV3xlA,Data Analyst vs Data Scientist | What to Choos...,Arsh Goyal,995,55,21,121000
44,DgGxmbCbBvc,Data Science Job Market Predictions for 2023 p...,Jay Feng,354,19,0,32500
45,Z79AqDouS-Y,How I'd Learn Data Science In 2023 (If I Could...,Data Nash,3139,233,35,4150
46,T08eJt9DlgU,Data Scientist vs Data Analyst - Which Is Righ...,CareerFoundry,10870,372,12,158000
47,pLon_Mit7sk,day in the life of a Business Analyst at Spoti...,Lillian Chiu,246153,6975,246,173000
48,HqoLnQ0X-F8,Full Data Science Roadmap for Beginner,Ayush Singh,47227,1889,117,35900
49,qrhRfPY4F4w,The most important skills of data scientists |...,TEDx Talks,250949,3889,94,37500000

# Analysis on the extracted data

Comparison metrics on the attributes Like_Count, View_Count, Subscriber_Count using various visualization librarires in python